[tool.ruff]
line-length = 88
target-version = "py313"

[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = []

[tool.pytest.ini_options]
pythonpath = "."
asyncio_mode = "auto"
addopts = "--disable-warnings"
